/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      white: '#FFFFFF',
      black: '#292929',
      red: '#EF5149',
      'red-1': '#FEEDED',
      'red-light-1': '#F2746D',
      'red-light-2': '#F59792',
      'red-light-3': '#F9B9B6',
      'red-light-4': '#FCDCDB',
      'red-dark-1': '#D74942',
      'red-dark-2': '#D74942',
      'red-dark-3': '#AE3B35',
      'red-dark-4': '#9D3530',
      'red-dark-5': '#EF4949',
      blue: '#499FEF',
      'blue-1': '#EDF6FE',
      orange: '#EF9949',
      'orange-1': '#FEF5ED',
      green: '#49EF9F',
      'green-1': '#EDFEF6',
      'gray-dark': '#797777',
      gray: '#AAAAAA',
      'gray-1': '#656565',
      'gray-light': '#E2E2E2',
      'gray-light-1': '#F5F5F5',
    },
    extend: {
      fontFamily: {},
      spacing: {
        1: '4px',
        2: '8px',
        2.5: '11px',
        3: '12px',
        4: '16px',
        5: '24px',
        6: '32px',
        7: '40px',
        8: '48px',
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '32px',
        '3xl': '40px',
      },
      lineHeight: {
        1: '18px',
        2: '21px',
        3: '24px',
        4: '27px',
        5: '30px',
        6: '48px',
        7: '60px',
      },
      // backgroundImage: {
      //   'bg-home-page': "url('/img/hero-pattern.svg')",
      // },
    },
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      DEFAULT: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      full: '9999px',
      large: '12px',
    },
  },
  plugins: [],
}
